package com.shaheen.entity;
// Generated Mar 29, 2020 4:46:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
public class Teacher extends Person implements java.io.Serializable {

    private Date hireDate;

    public Teacher() {
    }

    public Teacher(String firstName, String lastName, Date hireDate) {
        super(firstName, lastName);
        this.hireDate = hireDate;
    }

    public Date getHireDate() {
        return this.hireDate;
    }

    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
}
